--- 
services: 
  backend: 
    image: "592115518/se234-lab10-backend:latest"
    ports: 
      - "8082:8080"
  frontend: 
    image: "592115518/se234-lab10-client:latest"
    ports: 
      - "8081:80"
version: '3.3'
